apiVersion: v1
kind: Secret
metadata:
  name: ocrbase-secrets
  namespace: ocrbase
type: Opaque
stringData:
  BETTER_AUTH_SECRET: "AZfow1tr3uLWQb+LPJo3g3sLgCZ18erOXVWApW/SSNc="
---
apiVersion: v1
kind: Secret
metadata:
  name: llmhub-credentials
  namespace: ocrbase
type: Opaque
stringData:
  DB_PASSWORD: "3VABqyEGDilWFgQQ+6U5iouZ7OxPRjxI"
  MINIO_ROOT_PASSWORD: "CySJ2NTucN15mCcFu3hvfQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ocrbase
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"crepo.re-cloud.io":{"username":"cc","password":"bskSkOPLF4ziny5","auth":"Y2M6YnNrU2tPUExGNHppbnk1"}}}'
